### ISSUE TITLE
fix the circuit!

### ISSUE THREAD

**Issue by darleiv** [RBSC/F4-FMPAC#1]
438 / 5.000
Resultados de tradução
Please . fix the C6. that the poles are inverted and can cause an explosion in the user's hand. . and add 100nf coupling capacitors to each logic gate in the circuit this is a simple electronic rule. and put 47UF capacitors on the B+ 5V decoupling. when you put a project on google you should warn that it may contain errors in the circuit and it is in BETA version. This is missing from your GIT. See you soon
https://ibb.co/hYc2Wrp

**Comment by Wierzbowsky** [comment]
The circuit is correct. The C6 capacitor is connected to -12v rail, so its ground goes to the -12v and its plus goes to the ground.
The amount of decoupling capacitors is enough for this circuit. The 5v rail also has 10uF tantalum capacitor which is enough for filtering purposes. The circuit draws already stabilized power from the PSU, so it's not necessary to complicate the board with unnecessary components. This is not a BETA product, this is revision 1.4 that works very well on many computers out there.
